### ISSUE TITLE
Add patches and support/options for remaining SuperZZT features

### ISSUE THREAD

**Issue by TheRealHamtaro126** [asiekierka/OpenZoo#2]
So far I wanted what remains of SuperZZT compared to ZZT.

This is a key feature that is needed in order for SuperZZT (SUPERZ.EXE) to be built, if this is done. this should count as an enhancement as well as an addendum to the original source material, This includes Scrolling and Large Boards!

**Comment by asiekierka** [comment]
Super ZZT and ZZT's codebases are most likely divergent in the four key files (ELEMENTS/EDITOR/OOP/GAME); therefore, a recreation of Super ZZT would ideally be pursued separately, and then the changes transcribed from one codebase to the other with patches if so desired.

**Comment by TheRealHamtaro126** [comment]
I do understand that so far. Yes.

**Comment by asiekierka** [comment]
https://github.com/asiekierka/reconstruction-of-super-zzt

**Comment by TheRealHamtaro126** [comment]
Since there is already a reconstruction of Super ZZT, This is closed for comment, Thank you aise for doing the reconstructions!!!
